version: "3"

services:
  mysqldb:
    build:
      context: .
      dockerfile: docker/development/mysql/Dockerfile
    volumes:
       - ./db_data/development:/var/lib/mysql
    environment:
      MYSQL_DATABASE: opencart3
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    ports:
      - 3306:3306 
    networks:
      - back
      
      
  app:
    build:
      context: .
      dockerfile: docker/development/apache/Dockerfile
    volumes:
      - .:/var/www/html
    hostname: web.local
    depends_on:
      - mysqldb
    ports:
      - 80:80
      - 443:443
    networks:
      - back
  

networks:
  back:
    driver: bridge