version: "3"

services:
<<<<<<< HEAD
<<<<<<< HEAD
      

  mysqlmaster:
    build:
      context: .
      dockerfile: docker/development/mysql/Dockerfile
    volumes:
       - ./db_data/development:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cake3db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    ports:
      - 3306:3306 
    networks:
      - back
      
      
  app:
    build:
      context: .
      dockerfile: docker/development/apache/Dockerfile
    volumes:
      - ./app:/var/www/html
    hostname: web.local
    depends_on:
      - mysqlmaster
=======
=======
>>>>>>> ece486ed2118c688ae2353a9a01803aaa15f702d
  app:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    volumes:
      - .:/var/www/html
    hostname: web.local
<<<<<<< HEAD
>>>>>>> ece486ed2118c688ae2353a9a01803aaa15f702d
=======
>>>>>>> ece486ed2118c688ae2353a9a01803aaa15f702d
    ports:
      - 80:80
      - 443:443
    networks:
      - back
<<<<<<< HEAD
<<<<<<< HEAD
=======
      
>>>>>>> ece486ed2118c688ae2353a9a01803aaa15f702d
=======
      
>>>>>>> ece486ed2118c688ae2353a9a01803aaa15f702d
  

networks:
  back:
    driver: bridge