version: "3"

services:
      

  db:
    image: mysql:5.7
    volumes:
       - ./db_data/master:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cake3db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    ports:
      - 3306:3306 
    networks:
      - back
      
  db_slave:
    image: mysql:5.7
    depends_on:
      - db
    volumes:
       - ./db_data/slave:/var/lib/mysql
       - ./docker/production/mysql/slave/config:/etc/mysql/conf.d/
    environment:
      MYSQL_DATABASE: cake3db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
    expose:
    - 3307
    - 3306
    
    networks:
      - back
      
  app:
    build:
      context: .
      dockerfile: docker/production/apache/Dockerfile
    volumes:
      - ./app_data:/var/www/html
    hostname: web.local
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
      - 22:22
    networks:
      - back
  

networks:
  back:
    driver: bridge