version: "3"

services:
  mysqlmaster:
    image: mysql:5.7
    volumes:
       - ./db_data/master:/var/lib/mysql
       - ./docker/production/mysql/master/config:/etc/mysql/conf.d/
    hostname: mysqlmaster
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    ports:
      - 3306:3306 
    networks:
      - back
      
  mysqlslave:
    image: mysql:5.7
    depends_on:
      - mysqlmaster
    volumes:
       - ./db_data/slave:/var/lib/mysql
       - ./docker/production/mysql/slave/config:/etc/mysql/conf.d/
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    ports:
      - 3307:3306
    expose:
    - 3307
    - 3306
    
    networks:
      - back

      
  mysqlconfigure:
    build:
      context: .
      dockerfile: docker/production/mysql/configure/Dockerfile
    depends_on:
      - mysqlmaster
      - mysqlslave
    environment:
      - "MYSQL_SLAVE_PASSWORD=p4ssw0rd!"
      - "MYSQL_MASTER_PASSWORD=p4ssw0rd!"
      - "MYSQL_ROOT_PASSWORD=p4ssw0rd!"
      - "MYSQL_REPLICATION_USER=p4ssw0rd!"
      - "MYSQL_REPLICATION_PASSWORD=p4ssw0rd!"
    volumes:
      - ./docker/production/shell/mysql/:/tmp/shell/
    command: 
      - /tmp/shell/mysql_connector.sh
    networks:
      - back

  app:
    build:
      context: .
      dockerfile: docker/production/apache/Dockerfile
    volumes:
      - ./app_data:/var/www/html
    hostname: web.local
    depends_on:
      - mysqlmaster
    ports:
      - 80:80
      - 443:443
      - 22:22
    networks:
      - back
  

networks:
  back:
    driver: bridge